INSERT INTO public.subcategory (id, name, category_id) VALUES (1, 'Шампуни', 1);
INSERT INTO public.subcategory (id, name, category_id) VALUES (2, 'Бальзамы', 1);
INSERT INTO public.subcategory (id, name, category_id) VALUES (3, 'Кремы', 2);
INSERT INTO public.subcategory (id, name, category_id) VALUES (4, 'Тоники', 2);
INSERT INTO public.subcategory (id, name, category_id) VALUES (5, 'Помады', 3);
INSERT INTO public.subcategory (id, name, category_id) VALUES (6, 'Туши', 3);
INSERT INTO public.subcategory (id, name, category_id) VALUES (7, 'Женская', 4);
INSERT INTO public.subcategory (id, name, category_id) VALUES (8, 'Мужская', 4);
INSERT INTO public.subcategory (id, name, category_id) VALUES (9, 'Маски', 1);